

class KpiGimDebitPointeDataframe(Enum):
    JOURNEE = "JOURNEE"
    SITE = "SITE"
    COMBUSTIBLE = "COMBUSTIBLE"
    UNITE = "UNITE"
    VALEUR_PREVISIONNELLE = "VALEUR_PREVISIONNELLE"
    VALEUR_REELLE = "VALEUR_REELLE"
    VALEUR_CONSOLIDEE = "VALEUR_CONSOLIDEE"

